### PR TITLE
support for 12.5 build + ci

### PR DESCRIPTION
**Pull request by fruitybagel**
* boots in x86_64 **(built w/ XCode 13.4.1 13F100), both dev & release builds**
* Added single patch, corrects return value according to function ret type. In latest version I see that return value is already changed.
https://github.com/apple-oss-distributions/xnu/blob/1031c584a5e37aff177559b9f69dbd3c8c3fd30a/iokit/Kernel/IOBufferMemoryDescriptor.cpp#L332-L341

### CODE REVIEW

**Comment by blacktop** [comment]
nice! I'll try to build soon. We'll need to add it to the CI as well.  I think I want to move to a yml per-build setup instead of a single file that way it won't rebuild them all on changes etc

**Comment by fruitybagel** [comment]
Not entirely sure what's most fitting type of structure you got in mind have a look at the mock thingy. Technically there is less files I just wrote a script that generates ci definition per version from like a json and there is a separate templated build file `.github/workflows/template-xnu-build.yml`, maybe you might just need this one. Like you would turn off all the hooks I guess and can trigger any build with version input on demand thru UI? Idk whatever, it might be dumb but yeah , lmk

**Comment by fruitybagel** [comment]
Also probably you should lock this later somehow so it's not so easy to trigger pipeline changes idk :D

**Comment by blacktop** [comment]
> Also probably you should lock this later somehow so it's not so easy to trigger pipeline changes idk :D

I think you must have hacked GH? It was set to not allow workflows form first time contribs, might be a bug bounty in it for you ;)

**Comment by blacktop** [comment]
> Also probably you should lock this later somehow so it's not so easy to trigger pipeline changes idk :D

actually I think those pipeline runs are happening only in your fork on your account, so not mine (meaning GH is working correctly)

**Comment by fruitybagel** [comment]
yeah I was just surprised it let me run it like that or idk

**Comment by blacktop** [comment]
can you remove all the CI stuff from this PR please

**Comment by blacktop** [comment]
go ahead and rebase from `main` also

**Pull request closed without merging**
